import { Role, Language, Provider, Task, Order } from './types';

export const TRANSLATIONS: Record<Language, any> = {
  en: {
    login: 'Login',
    register: 'Register',
    email: 'Email',
    continueGoogle: 'Continue with Google',
    continueApple: 'Continue with Apple',
    selectRole: 'Select Your Role',
    farmer: 'Farmer',
    tractorDriver: 'Tractor Driver',
    fertilizerProvider: 'Fertilizer Provider',
    agronomist: 'Agronomist',
    waterSupplier: 'Water Supplier',
    onboarding: 'Onboarding',
    name: 'Name',
    surname: 'Surname',
    age: 'Age',
    location: 'Location',
    experience: 'Experience (Years)',
    next: 'Next',
    fieldSetup: 'Field Setup',
    cropType: 'Crop Type',
    plantingDate: 'Planting Date',
    landSize: 'Land Size (m²)',
    soilType: 'Soil Type',
    irrigationMethod: 'Irrigation Method',
    expectedAmount: 'Expected Amount (kg)',
    dashboard: 'Dashboard',
    calendar: 'Calendar',
    growthTracking: 'Growth Tracking',
    marketplace: 'Marketplace',
    profile: 'Profile',
    chat: 'Chat',
    orders: 'Orders',
    rankings: 'Rankings',
    settings: 'Settings',
    darkMode: 'Dark Mode',
    language: 'Language',
    logout: 'Logout',
    book: 'Book',
    filter: 'Filter',
    price: 'Price',
    rating: 'Rating',
    top100: 'TOP 100',
    aiHelp: 'AI Help',
    askAi: 'Ask AI...',
    plowing: 'Plowing',
    watering: 'Watering',
    planting: 'Planting',
    harvesting: 'Harvesting',
    growthStage: 'Growth Stage',
    weatherInfluence: 'Weather Influence',
    riskIfSkipped: 'Risk if skipped',
    explanation: 'Explanation',
    daysSincePlanting: 'Days since planting',
    serviceType: 'Service Type',
    equipment: 'Equipment / Expertise',
    workingHours: 'Working Hours',
    minLandSize: 'Min Land Size',
    maxLandSize: 'Max Land Size',
    extraConditions: 'Extra Conditions',
    acceptedJobs: 'Accepted Jobs',
    farmerName: 'Farmer Name',
    typeOfWork: 'Type of Work',
    notes: 'Notes',
    time: 'Time',
    welcomeBack: 'Welcome back',
    sunny: 'Sunny',
    humidity: 'Humidity',
    status: 'Status',
    pending: 'Pending',
    completed: 'Completed',
    accepted: 'Accepted',
    gotIt: 'Got it',
    decline: 'Decline',
    acceptJob: 'Accept Job',
    all: 'All',
    productivity: 'Productivity',
    online: 'Online',
    enterName: 'Enter your name',
    enterSurname: 'Enter your surname',
    enterAge: 'Enter your age',
    yearsExp: 'Years of experience',
    currentLoc: 'Current Location',
    autoDetected: 'Auto-detected',
    targetYield: 'Target yield in kg',
    areaM2: 'Area in m²',
    cotton: 'Cotton',
    wheat: 'Wheat',
    flowering: 'Flowering',
    daysLiving: 'Days Living',
    target: 'Target',
    noTasks: 'No tasks for this day',
    reason: 'Reason',
    importance: 'Importance',
    upcomingActions: 'Upcoming Actions',
    task1_exp: 'Soil moisture is low due to recent heatwave.',
    task1_growth: 'Vegetative',
    task1_weather: 'High evaporation rate expected.',
    task1_risk: 'Stunted growth and leaf wilting.',
    task2_exp: 'Prepare soil for next planting phase.',
    task2_growth: 'Pre-planting',
    task2_weather: 'Ideal soil moisture for tilling.',
    task2_risk: 'Poor root penetration.',
    task3_exp: 'Regular irrigation to maintain optimal growth.',
    task3_growth: 'Flowering',
    task3_weather: 'Dry winds expected.',
    task3_risk: 'Flower drop and reduced yield.',
    task4_exp: 'Check for pests and diseases in the field.',
    task4_growth: 'Fruiting',
    task4_weather: 'Humid conditions favor fungi.',
    task4_risk: 'Uncontrolled spread of infection.',
  },
  ru: {
    login: 'Войти',
    register: 'Регистрация',
    email: 'Электронная почта',
    continueGoogle: 'Продолжить с Google',
    continueApple: 'Продолжить с Apple',
    selectRole: 'Выберите вашу роль',
    farmer: 'Фермер',
    tractorDriver: 'Тракторист',
    fertilizerProvider: 'Поставщик удобрений',
    agronomist: 'Агроном',
    waterSupplier: 'Поставщик воды',
    onboarding: 'Личные данные',
    name: 'Имя',
    surname: 'Фамилия',
    age: 'Возраст',
    location: 'Местоположение',
    experience: 'Опыт (лет)',
    next: 'Далее',
    fieldSetup: 'Настройка поля',
    cropType: 'Тип культуры',
    plantingDate: 'Дата посадки',
    landSize: 'Размер участка (м²)',
    soilType: 'Тип почвы',
    irrigationMethod: 'Метод полива',
    expectedAmount: 'Ожидаемый урожай (кг)',
    dashboard: 'Дашборд',
    calendar: 'Календарь',
    growthTracking: 'Отслеживание роста',
    marketplace: 'Маркетплейс',
    profile: 'Профиль',
    chat: 'Чат',
    orders: 'Заказы',
    rankings: 'Рейтинги',
    settings: 'Настройки',
    darkMode: 'Темная тема',
    language: 'Язык',
    logout: 'Выйти',
    book: 'Забронировать',
    filter: 'Фильтр',
    price: 'Цена',
    rating: 'Рейтинг',
    top100: 'ТОП 100',
    aiHelp: 'ИИ Помощь',
    askAi: 'Спросить ИИ...',
    plowing: 'Вспашка',
    watering: 'Полив',
    planting: 'Посадка',
    harvesting: 'Сбор урожая',
    growthStage: 'Стадия роста',
    weatherInfluence: 'Влияние погоды',
    riskIfSkipped: 'Риск при пропуске',
    explanation: 'Объяснение',
    daysSincePlanting: 'Дней с момента посадки',
    serviceType: 'Тип услуги',
    equipment: 'Оборудование / Экспертиза',
    workingHours: 'Рабочие часы',
    minLandSize: 'Мин. размер участка',
    maxLandSize: 'Макс. размер участка',
    extraConditions: 'Доп. условия',
    acceptedJobs: 'Принятые работы',
    farmerName: 'Имя фермера',
    typeOfWork: 'Тип работы',
    notes: 'Заметки',
    time: 'Время',
    welcomeBack: 'С возвращением',
    sunny: 'Солнечно',
    humidity: 'Влажность',
    status: 'Статус',
    pending: 'В ожидании',
    completed: 'Завершено',
    accepted: 'Принято',
    gotIt: 'Понятно',
    decline: 'Отклонить',
    acceptJob: 'Принять работу',
    all: 'Все',
    productivity: 'Продуктивность',
    online: 'В сети',
    enterName: 'Введите ваше имя',
    enterSurname: 'Введите вашу фамилию',
    enterAge: 'Введите ваш возраст',
    yearsExp: 'Лет опыта',
    currentLoc: 'Текущее местоположение',
    autoDetected: 'Определено автоматически',
    targetYield: 'Целевой урожай в кг',
    areaM2: 'Площадь в м²',
    cotton: 'Хлопок',
    wheat: 'Пшеница',
    flowering: 'Цветение',
    daysLiving: 'Дней жизни',
    target: 'Цель',
    noTasks: 'Нет задач на этот день',
    reason: 'Причина',
    importance: 'Важность',
    upcomingActions: 'Предстоящие действия',
    task1_exp: 'Влажность почвы низкая из-за недавней жары.',
    task1_growth: 'Вегетативный',
    task1_weather: 'Ожидается высокая скорость испарения.',
    task1_risk: 'Задержка роста и увядание листьев.',
    task2_exp: 'Подготовьте почву для следующего этапа посадки.',
    task2_growth: 'Предпосадочный',
    task2_weather: 'Идеальная влажность почвы для вспашки.',
    task2_risk: 'Плохое проникновение корней.',
    task3_exp: 'Регулярный полив для поддержания оптимального роста.',
    task3_growth: 'Цветение',
    task3_weather: 'Ожидаются сухие ветры.',
    task3_risk: 'Опадание цветов и снижение урожайности.',
    task4_exp: 'Проверьте поле на наличие вредителей и болезней.',
    task4_growth: 'Плодоношение',
    task4_weather: 'Влажные условия благоприятствуют грибкам.',
    task4_risk: 'Неконтролируемое распространение инфекции.',
  },
  uz: {
    login: 'Kirish',
    register: 'Ro\'yxatdan o\'tish',
    email: 'Elektron pochta',
    continueGoogle: 'Google bilan davom etish',
    continueApple: 'Apple bilan davom etish',
    selectRole: 'Rolingizni tanlang',
    farmer: 'Dehqon',
    tractorDriver: 'Traktorchi',
    fertilizerProvider: 'O\'g\'it yetkazib beruvchi',
    agronomist: 'Agronom',
    waterSupplier: 'Suv yetkazib beruvchi',
    onboarding: 'Shaxsiy ma\'lumotlar',
    name: 'Ism',
    surname: 'Familiya',
    age: 'Yosh',
    location: 'Manzil',
    experience: 'Tajriba (yil)',
    next: 'Keyingi',
    fieldSetup: 'Dala sozlamalari',
    cropType: 'Ekin turi',
    plantingDate: 'Ekish sanasi',
    landSize: 'Yer maydoni (m²)',
    soilType: 'Tuproq turi',
    irrigationMethod: 'Sug\'orish usuli',
    expectedAmount: 'Kutilayotgan hosil (kg)',
    dashboard: 'Boshqaruv paneli',
    calendar: 'Taqvim',
    growthTracking: 'O\'sishni kuzatish',
    marketplace: 'Bozor',
    profile: 'Profil',
    chat: 'Suhbat',
    orders: 'Buyurtmalar',
    rankings: 'Reytinglar',
    settings: 'Sozlamalar',
    darkMode: 'Tungi rejim',
    language: 'Til',
    logout: 'Chiqish',
    book: 'Band qilish',
    filter: 'Saralash',
    price: 'Narx',
    rating: 'Reyting',
    top100: 'TOP 100',
    aiHelp: 'AI Yordam',
    askAi: 'AI dan so\'rang...',
    plowing: 'Haydash',
    watering: 'Sug\'orish',
    planting: 'Ekish',
    harvesting: 'Hosil yig\'ish',
    growthStage: 'O\'sish bosqichi',
    weatherInfluence: 'Ob-havo ta\'siri',
    riskIfSkipped: 'O\'tkazib yuborilsa xavf',
    explanation: 'Tushuntirish',
    daysSincePlanting: 'Ekilganidan beri kunlar',
    serviceType: 'Xizmat turi',
    equipment: 'Uskunalar / Tajriba',
    workingHours: 'Ish vaqti',
    minLandSize: 'Minimal yer maydoni',
    maxLandSize: 'Maksimal yer maydoni',
    extraConditions: 'Qo\'shimcha shartlar',
    acceptedJobs: 'Qabul qilingan ishlar',
    farmerName: 'Dehqon ismi',
    typeOfWork: 'Ish turi',
    notes: 'Eslatmalar',
    time: 'Vaqt',
    welcomeBack: 'Xush kelibsiz',
    sunny: 'Quyoshli',
    humidity: 'Namlik',
    status: 'Holat',
    pending: 'Kutilmoqda',
    completed: 'Bajarildi',
    accepted: 'Qabul qilindi',
    gotIt: 'Tushunarli',
    decline: 'Rad etish',
    acceptJob: 'Ishni qabul qilish',
    all: 'Hammasi',
    productivity: 'Mahsuldorlik',
    online: 'Onlayn',
    enterName: 'Ismingizni kiriting',
    enterSurname: 'Familiyangizni kiriting',
    enterAge: 'Yoshingizni kiriting',
    yearsExp: 'Tajriba yillari',
    currentLoc: 'Joriy manzil',
    autoDetected: 'Avtomatik aniqlandi',
    targetYield: 'Maqsadli hosil (kg)',
    areaM2: 'Maydon (m²)',
    cotton: 'Paxta',
    wheat: 'Bug\'doy',
    flowering: 'Gullash',
    daysLiving: 'Yashash kunlari',
    target: 'Maqsad',
    noTasks: 'Bu kun uchun vazifalar yo\'q',
    reason: 'Sabab',
    importance: 'Muhimlik',
    upcomingActions: 'Kelgusi harakatlar',
    task1_exp: 'Yaqinda sodir bo\'lgan issiqlik to\'lqini tufayli tuproq namligi past.',
    task1_growth: 'Vegetativ',
    task1_weather: 'Yuqori bug\'lanish tezligi kutilmoqda.',
    task1_risk: 'O\'sishning to\'xtashi va barglarning so\'lishi.',
    task2_exp: 'Tuproqni keyingi ekish bosqichiga tayyorlang.',
    task2_growth: 'Ekishdan oldin',
    task2_weather: 'Haydash uchun ideal tuproq namligi.',
    task2_risk: 'Ildizning yomon kirib borishi.',
    task3_exp: 'Optimal o\'sishni ta\'minlash uchun muntazam sug\'orish.',
    task3_growth: 'Gullash',
    task3_weather: 'Quruq shamollar kutilmoqda.',
    task3_risk: 'Gullarning to\'kilishi va hosilning kamayishi.',
    task4_exp: 'Dalada zararkunandalar va kasalliklarni tekshiring.',
    task4_growth: 'Meva berish',
    task4_weather: 'Nam sharoit zamburug\'lar uchun qulay.',
    task4_risk: 'Infeкtsiyaning nazoratsiz tarqalishi.',
  },
};

export const MOCK_PROVIDERS: Provider[] = [
  {
    id: '1',
    name: 'Azizbek Karimov',
    role: 'Agronomist',
    rating: 4.9,
    location: 'Tashkent Region',
    services: ['Soil Analysis', 'Pest Control'],
    price: '50,000 UZS / m²',
    photo: 'https://picsum.photos/seed/aziz/200/200',
  },
  {
    id: '2',
    name: 'Dilshod Umarov',
    role: 'Tractor Driver',
    rating: 4.7,
    location: 'Samarkand Region',
    services: ['Plowing', 'Harvesting'],
    price: '150,000 UZS / hour',
    photo: 'https://picsum.photos/seed/dilshod/200/200',
  },
  {
    id: '3',
    name: 'Nodira Alieva',
    role: 'Fertilizer Provider',
    rating: 4.8,
    location: 'Fergana Valley',
    services: ['Organic Fertilizers', 'Nitrogen'],
    price: '200,000 UZS / bag',
    photo: 'https://picsum.photos/seed/nodira/200/200',
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: '1',
    date: '2026-04-06',
    type: 'watering',
    explanation: 'task1_exp',
    growthStage: 'task1_growth',
    weatherInfluence: 'task1_weather',
    riskIfSkipped: 'task1_risk',
    status: 'pending',
  },
  {
    id: '2',
    date: '2026-04-08',
    type: 'plowing',
    explanation: 'task2_exp',
    growthStage: 'task2_growth',
    weatherInfluence: 'task2_weather',
    riskIfSkipped: 'task2_risk',
    status: 'pending',
  },
  {
    id: '3',
    date: '2026-04-12',
    type: 'watering',
    explanation: 'task3_exp',
    growthStage: 'task3_growth',
    weatherInfluence: 'task3_weather',
    riskIfSkipped: 'task3_risk',
    status: 'pending',
  },
  {
    id: '4',
    date: '2026-04-15',
    type: 'planting',
    explanation: 'task2_exp',
    growthStage: 'task2_growth',
    weatherInfluence: 'task2_weather',
    riskIfSkipped: 'task2_risk',
    status: 'pending',
  },
  {
    id: '5',
    date: '2026-04-18',
    type: 'watering',
    explanation: 'task3_exp',
    growthStage: 'task3_growth',
    weatherInfluence: 'task3_weather',
    riskIfSkipped: 'task3_risk',
    status: 'pending',
  },
  {
    id: '6',
    date: '2026-04-22',
    type: 'harvesting',
    explanation: 'task4_exp',
    growthStage: 'task4_growth',
    weatherInfluence: 'task4_weather',
    riskIfSkipped: 'task4_risk',
    status: 'pending',
  },
  {
    id: '7',
    date: '2026-04-25',
    type: 'planting',
    explanation: 'task4_exp',
    growthStage: 'task4_growth',
    weatherInfluence: 'task4_weather',
    riskIfSkipped: 'task4_risk',
    status: 'pending',
  },
  {
    id: '8',
    date: '2026-04-28',
    type: 'watering',
    explanation: 'task3_exp',
    growthStage: 'task3_growth',
    weatherInfluence: 'task3_weather',
    riskIfSkipped: 'task3_risk',
    status: 'pending',
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: '1',
    farmerName: 'Jasur Bek',
    location: 'Bukhara, Gijduvan',
    typeOfWork: 'Plowing',
    time: '09:00',
    date: '2026-04-07',
    landSize: 5000,
    notes: 'Heavy soil, needs deep plowing.',
    status: 'accepted',
  },
];
